@hostname=localhost
@port=8087
@baseURL=http://{{hostname}}:{{port}}

###
GET {{baseURL}}/hello

###
GET {{baseURL}}/hello/formula

###
GET {{baseURL}}/date/today
###
POST {{baseURL}}/date/today

###
POST {{baseURL}}/employee/45

###
GET {{baseURL}}/method
###
POST {{baseURL}}/method
###
PUT {{baseURL}}/method
###
DELETE {{baseURL}}/method
###
GET {{baseURL}}/context
###
GET {{baseURL}}/headers
###
GET {{baseURL}}/var?foo=1&foo=2&test&tata=toto
###
GET {{baseURL}}/var#frag/test
###
GET {{baseURL}}/redirect
###
GET {{baseURL}}/404
###
GET {{baseURL}}/404JSON
###
POST {{baseURL}}/headerSup

###
GET {{baseURL}}/404ImagePath
###
GET {{baseURL}}/404ImageD
###
GET {{baseURL}}/404TextD
###
GET {{baseURL}}/404Html
###
GET {{baseURL}}/format
Accept: text/html
###
GET {{baseURL}}/format
Accept: application/json
###
GET {{baseURL}}/format
Accept: application/xml
###
GET {{baseURL}}/format
###
GET {{baseURL}}/format
Accept: text/plain
###
GET {{baseURL}}/attachment
###
GET {{baseURL}}/router.http
